# this file contains the configuration structure for the ApexMS project

metadata:
    version: 1.0
    project: ApexMS
    description: "ApexMS configuration file"

environments:
    flask-app:
        - FLASK_APP=app.py
        - FLASK_ENV=development
        - FLASK_DEBUG=true
        - FLASK_RUN_HOST=localhost

    database:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=apexms
        - MYSQL_USER=apexms
        - MYSQL_PASSWORD=apexms

    django-app:
        - DJANGO_SETTINGS_MODULE=apexms.settings
        - DJANGO_SECRET_KEY=123

    redis:
        - REDIS_HOST=localhost
        - REDIS_PORT=6379

    postgres-db:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=apexms

services:
    flask-app:
        framework: flask
        port: 5000
        environments:
            - flask-app
            - database
        databases:
            - mysql
        networks:
            - apexms-network
        cache:
            - redis
        messagebrokers:
            - rabbitmq
        dependon:
            - database
            - redis
            - rabbitmq

    django-app:
        framework: django
        port: 8000
        environments:
            - django-app
            - postgres-db
            - redis
        databases:
            - postgres-db
        networks:
            - apexms-network
        cache:
            - redis
        dependon:
            - postgres-db
            - redis

    fast-api:
        framework: fastapi
        port: 8001
        environments:
            - flask-app
            - redis
        environment:
            - REDIS_HOST=localhost
            - REDIS_PORT=6379
        networks:
            - apexms-network
        messagebrokers:
            - rabbitmq
        cache:
            - redis
        dependon:
            - redis
            - rabbitmq

databases:
    postgres-db:
        type: postgresql
        image: postgresql:latest
        ports:
            - 5432:5432
        environments:
            - postgres-db
        # volumes:
        #     - postgres-data
        networks:
            - apexms-network

    database:
        type: mysql
        ports:
            - 3306:3306
        networks:
            - apexms-network
        environments:
            - database
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=apexms
            - MYSQL_USER=apexms
            - MYSQL_PASSWORD=apexms
        volumes:
            - mysql-data

messagebrokers:
    rabbitmq:
        type: rabbitmq
        image: rabbitmq
        ports:
            - 5672:5672
        networks:
            - apexms-network
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest

containers:
    redis:
        image: redis
        ports:
            - 6379:6379
        networks:
            - apexms-network
        environments:
            - redis

networks:
    - apexms-network

volumes:
    - mysql-data
    # - postgres-data

git:
    repositories:
        django-app:
            remoteurl: test.com/django-app.git
            mainbranch: main
            initbranches:
                - dev
                - feature

        flask-app:
            remoteurl: test.com/flask-app.git
            mainbranch: main
            initbranches:
                - dev
                - feature

        fast-api:
            remoteurl: test.com/fast-api.git
            mainbranch: main
            initbranches:
                - dev
                - feature

    full-project:
        remoteurl: test.com/apexms.git
        mainbranch: main
        initbranches:
            - dev
            - feature
